var SOFTWARE_FEATURE_CONST = {
		READ_ALL_ORGANIZATION : 0,
		READ_ASSIGNED_ORGANIZATION : 1,
		

		ADD_ANALYTICS : 2,
		EDIT_ANALYTICS : 3,
		DELETE_ANALYTICS : 4,


		ADD_CITY : 2,
		EDIT_CITY : 3,
		DELETE_CITY : 4,


		ADD_COUNTRY : 2,
		EDIT_COUNTRY : 3,
		DELETE_COUNTRY : 4,


		ADD_CURRENCY : 2,
		EDIT_CURRENCY : 3,
		DELETE_CURRENCY : 4,


		ADD_LOOKUP : 2,
		EDIT_LOOKUP : 3,
		DELETE_LOOKUP : 4,


		ADD_LOOKUP_GROUP : 2,
		EDIT_LOOKUP_GROUP : 3,
		DELETE_LOOKUP_GROUP : 4,


		ADD_ORGANIZATION : 2,
		EDIT_ORGANIZATION : 3,
		DELETE_ORGANIZATION : 4,


		ADD_ORGANIZATION_SYS_USER_MAP : 2,
		EDIT_ORGANIZATION_SYS_USER_MAP : 3,
		DELETE_ORGANIZATION_SYS_USER_MAP : 4,


		ADD_ROLE : 2,
		EDIT_ROLE : 3,
		DELETE_ROLE : 4,


		ADD_SUBSCRIBER : 2,
		EDIT_SUBSCRIBER : 3,
		DELETE_SUBSCRIBER : 4,


		ADD_SYSTEM_ISSUE : 2,
		EDIT_SYSTEM_ISSUE : 3,
		DELETE_SYSTEM_ISSUE : 4,


		ADD_SYS_USER : 2,
		EDIT_SYS_USER : 3,
		DELETE_SYS_USER : 4,


}

